# yaml-language-server: $schema=https://raw.githubusercontent.com/megalinter/megalinter/main/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
# ref: <https://megalinter.io/latest/config-file/>

EXTENDS:
  - https://github.com/liblaf/repo/raw/refs/heads/main/.github/linters/.mega-linter.yaml
