# yaml-language-server: $schema=https://raw.githubusercontent.com/googleapis/repo-automation-bots/main/packages/auto-label/src/config-schema.json

language:
  pullrequest: true
  labelprefix: "lang: "

path:
  pullrequest: true
  paths:
    docs: "type: docs"

staleness:
  pullrequest: true

requestsize:
  enabled: true
