# yaml-language-server: $schema=https://raw.githubusercontent.com/googleapis/repo-automation-bots/main/packages/blunderbuss/src/config-schema.json

assign_issues:
  - liblaf

assign_prs:
  - liblaf

ignore_authors:
  - dependabot[bot]
  - pre-commit-ci[bot]
  - renovate[bot]
