# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: uv-export
        name: uv export
        entry: uv export --output-file requirements.txt
        language: system
        files: uv.lock
        pass_filenames: false
