# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: uv-export
        name: uv export
        entry: uv export --all-extras --no-dev --no-hashes --output-file requirements.lock
        language: system
        files: uv.lock
        pass_filenames: false
      - id: uv-export-dev
        name: uv export (dev)
        entry: uv export --all-extras --no-hashes --output-file requirements-dev.lock
        language: system
        files: uv.lock
        pass_filenames: false
