version: 2

python:
  install:
    - requirements: requirements-dev.lock

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
  jobs:
    # ref: <https://docs.readthedocs.io/en/stable/build-customization.html#unshallow-git-clone>
    post_checkout:
      - git fetch --unshallow || true

mkdocs:
  configuration: mkdocs.yaml
