# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Route Rules
site_url:
  !ENV [
    SITE_URL,
    READTHEDOCS_CANONICAL_URL,
    https://liblaf.github.io/route-rules/,
  ]
repo_name: liblaf/route-rules
repo_url: https://github.com/liblaf/route-rules
site_author: liblaf
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    # - navigation.footer
    # - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: system preference
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: dark mode

plugins:
  # Built-in plugins
  # - optimize
  - search
  - social
  # External plugins, schema provided by us
  - gen-files:
      scripts:
        - scripts/docs/gen-stats.py
        - scripts/docs/gen-ref-pages.py
  - git-committers:
      enabled: !ENV [READTHEDOCS, CI, false]
      repository: liblaf/route-rules
      branch: main
  - literate-nav
  - section-index
  # External plugins, schema provided by our community
  - git-revision-date-localized:
      enable_creation_date: true
  - mkdocstrings:
      default_handler: python
      enable_inventory: true
      handlers:
        python:
          import:
            - https://anyio.readthedocs.io/en/stable/objects.inv
            - https://boltons.readthedocs.io/en/stable/objects.inv
            - https://docs.pydantic.dev/latest/objects.inv
            - https://docs.python.org/3/objects.inv
            - https://humanize.readthedocs.io/en/stable/objects.inv
            - https://loguru.readthedocs.io/en/stable/objects.inv
            - https://rich.readthedocs.io/en/stable/objects.inv
            - https://ubelt.readthedocs.io/en/stable/objects.inv
            - https://validators.readthedocs.io/en/stable/objects.inv
          options:
            # General
            show_source: false
            # Headings
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            # Members
            inherited_members: true
            filters:
              - "!^_[^_]"
              - "!__all__"
            summary: true
            # Docstrings
            docstring_section_style: list
            show_if_no_docstring: true
            # Signatures
            show_signature_annotations: true
            separate_signature: true
            signature_crossrefs: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

watch:
  - docs/
  - scripts/docs/
  - src/sbr/
