#!/bin/bash
# This file is @generated by <https://github.com/liblaf/copier-python>.
# DO NOT EDIT!
set -o errexit
set -o nounset
set -o pipefail

function in-ci() {
  if [[ -n ${CI:-} ]]; then
    return 0
  else
    return 1
  fi
}

function needs-gpu() {
  for pkg in jax torch warp; do
    if python -c "import $pkg" &> /dev/null; then
      return 0
    fi
  done
  return 1
}

# ref: <https://github.com/scientific-python/lazy-loader#early-failure>
export EAGER_IMPORT=1

if needs-gpu; then
  numprocesses='0'
else
  numprocesses='auto'
fi

if in-ci; then
  # ref: <https://docs.codecov.com/docs/test-analytics#1-output-a-junit-xml-file-in-your-ci>
  pytest \
    --junit-xml='junit.xml' --override-ini junit_family=legacy \
    --cov --cov-branch \
    --numprocesses "$numprocesses" \
    "$@"
else
  pytest --numprocesses "$numprocesses" "$@"
fi
