#!/bin/bash
# This file is @generated by <https://github.com/liblaf/copier-python>.
# DO NOT EDIT!
# [MISE] depends_post=["lint"]
set -o errexit
set -o nounset
set -o pipefail

function has() {
  type "$@" &> /dev/null
}

if [[ -f 'pixi.lock' ]]; then
  pixi='pixi'
  if has pixi-wrapper.sh; then pixi='pixi-wrapper.sh'; fi
  "$pixi" upgrade "$@"
fi

if [[ -f 'uv.lock' ]]; then
  uv_sync=(uv sync)
  if has uv-sync.sh; then uv_sync=(uv-sync.sh); fi
  "${uv_sync[@]}" --upgrade "$@"
fi
