#!/bin/bash
# This file is @generated by <https://github.com/liblaf/copier-python>.
# DO NOT EDIT!

pushd "$(git rev-parse --show-toplevel)" > /dev/null || return 1

function has() {
  type "$@" &> /dev/null
}

if [[ -f 'pixi.lock' ]]; then
  options=()
  if [[ -t 2 ]]; then
    options+=(--color=always)
  fi
  pixi='pixi'
  if has pixi-wrapper.sh; then pixi='pixi-wrapper.sh'; fi
  eval "$("$pixi" shell-hook "${options[@]}")"
fi

if [[ -f 'uv.lock' ]]; then
  uv_sync=(uv sync)
  if has uv-sync.sh; then uv_sync=(uv-sync.sh); fi
  "${uv_sync[@]}"
  # shellcheck disable=SC1091
  source '.venv/bin/activate'
fi

popd > /dev/null || return 1
