name: CI

on:
  push:
    branches-ignore:
      - assets**
      - dist**
      - gh-pages
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Prettier
        run: npm install --global prettier
      - name: Install mise
        uses: jdx/mise-action@v3
      - name: Setup Python
        uses: liblaf/actions-ts/setup-python@dist
      - name: Build
        run: mise run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    name: Deploy
    permissions:
      contents: write
    needs:
      - build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Download Artifacts
        uses: actions/download-artifact@v5
        with:
          name: dist
          path: dist
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: dist
          single-commit: true
