name: CI

on:
  push:
  schedule:
    - cron: "0 0 * * *"

env:
  UV_INDEX_URL: https://pypi.org/simple

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v3
      - name: Install sing-box
        run: bash <(curl -fsSL https://sing-box.app/deb-install.sh)
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Install Dependencies
        run: uv sync --all-extras
      - name: Build Rule Sets
        run: |-
          uv run scripts/build.py
          bash scripts/compile.sh
          npx prettier --write --ignore-path "" output/README.md
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sing
          path: output/

  deploy:
    name: Deploy
    permissions:
      contents: write
    needs:
      - build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: sing
          path: sing/
      - name: Deploy to GitHub Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ github.token }}
          publish_branch: sing
          publish_dir: sing
          force_orphan: true
